[workspace]
members = [
    "ckb-lib-secp256k1",
    "contracts/otx-sighash-lock"
]
exclude = ["tests"]

[profile.release]
overflow-checks = true
strip = true
opt-level = 's'
lto = false
codegen-units = 1
