[package]
name = "ckb-lib-secp256k1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-std = "0.13.0"

[build-dependencies]
blake2b-rs = "0.2.0"
